#include<iostream.h>
#include<conio.h>
class ratio
{
public:
ratio()
{
cout<<"\n object born";
}
void display()
{
cout<<"\n object is alive";
}


~ratio()
{
cout<<"\n object dies";
}


};
void main()
{
clrscr();
{
ratio X;
X.display();
}
getch();
}

/*

 object born
 object is alive
 object dies

*/
                                                                                

                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                


